name: Publish on AWS CodeArtifact

on:
  push:
    branches:
      - develop

jobs:
  deploy:
   name: Publish on AWS CodeArtifact
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wheel twine
    - name: Build the library
      run: |
        python setup.py build_ext
        python setup.py bdist_wheel
    - name: Publish to CodeArtifact
      run: |
        export CODEARTIFACT_TOKEN=$(aws codeartifact get-authorization-token --domain clearbox-ai --query authorizationToken --output text)
        export CODEARTIFACT_REPOSITORY_ENDPOINT=$(aws codeartifact get-repository-endpoint --domain clearbox-ai --repository engine --format pypi --query repositoryEndpoint --output text)
        twine upload --repository-url $CODEARTIFACT_REPOSITORY_ENDPOINT --username aws --password $CODEARTIFACT_TOKEN dist/*