name: Test and Publish Library to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt
      - name: Run Python tests
        run: |
          pip install pytest
          pytest
      - name: Build Python wheels
        run: |
          python setup.py sdist bdist_wheel
      - name: Repair manylinux wheels
        if: runner.os == 'Linux'
        run: |
          pip install auditwheel
          mkdir wheels
          for whl in dist/*.whl; do
            auditwheel repair "$whl" --plat manylinux2014_x86_64 -w wheels
          done
          mv wheels/*.whl dist/
  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]  #  <- Still need to pick ONE version.
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Twine
        run: |
          pip install twine
      - name: Publish to PyPI
        run: |
          twine upload dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
